### ISSUE TITLE
Issues installing requirements and some more

### ISSUE THREAD

**Issue by DhruvaRajwade** [divnori/rnaflow#1]
For the pip dependencies, `dlllogger`, `openmm`==0.2 and the specific version for `torch-cluster` all throw errors.

`dlllogger` can be installed by `pip install 'git+https://github.com/NVIDIA/dllogger.git'` (the SE3 transformer installer installs this, I think removing` dlllogger` entirely from the `environment.yml` file will fix this). 

`torch-scatter` and `torch-cluster` throw CUDA mismatch errors if the local CUDA is not 11.7. To save myself the trouble of downloading and setting up CUDA 11.7, I just installed these through conda-forge instead of Pypi. 

`python rnaflow/data/process_data.py` this command fails to download any PDBs, adding the following to the `load_and_filter` function fixed it.

```Python
if not os.path.exists(pdb_out_dir):
        os.makedirs(pdb_out_dir)
```

The code seems to work other than this, really loved reading the paper! For PDB IDs that don't have `.PDB` available, is something else done to get them in `CIF` or some other format? Or are they not included in the dataset?

**Comment by divnori** [comment]
Thank you for these corrections; the code has been updated. We currently only include `.pdb` files in the dataset.
