### ISSUE TITLE
How do I inference my own files?

### ISSUE THREAD

**Issue by wenhuihuang19791109** [divnori/rnaflow#2]
Hi, supposed I have my own pdb file which contains my own rna and peptides interaction prediction, how do I that this pipeline to inference? thanks.

**Comment by divnori** [comment]
Hello, I apologize for the delayed response. Please see the new tutorial notebook for information on how to design your own RNAs given a target protein pocket sequence, backbone structure, and desired RNA length. These can be extracted from your pdb file. Thanks.
